var option_1 = require("../domain/option");
var ability_1 = require("../domain/ability");
var brand_1 = require("../domain/brand");
var gear_1 = require("../domain/gear");
exports.ALL_ABILITIES = {
    DamegeUp: new ability_1.default("damage_up", "攻撃力アップ", false),
    DefenceUp: new ability_1.default("defence_up", "防御力アップ", false),
    InkSaverMain: new ability_1.default("ink_saver_main", "インク効率アップ（メイン）", false),
    InkSaverSub: new ability_1.default("ink_saver_sub", "インク効率アップ（サブ）", false),
    InkRecoveryUp: new ability_1.default("ink_recovery_up", "インク回復力アップ", false),
    RunSpeedUp: new ability_1.default("run_speed_up", "ヒト移動速度アップ", false),
    SwimSpeedUp: new ability_1.default("swim_speed_up", "イカダッシュ速度アップ", false),
    SpecialChargeUp: new ability_1.default("special_charge_up", "スペシャル増加量アップ", false),
    SpecialDurationUp: new ability_1.default("special_duration_up", "スペシャル時間延長", false),
    QuickRespawn: new ability_1.default("quick_respawn", "復活時間短縮", false),
    SpecialSaver: new ability_1.default("special_saver", "スペシャル減少量ダウン", false),
    QuickSuperJump: new ability_1.default("quick_super_jump", "スーパージャンプ時間短縮", false),
    BombRangeUp: new ability_1.default("bomb_range_up", "ボム飛距離アップ", true),
    OpeningGambit: new ability_1.default("opening_gambit", "スタートダッシュ", true),
    LastDitchEffort: new ability_1.default("last_ditch_effort", "ラストスパート", true),
    Tenacity: new ability_1.default("tenacity", "逆境強化", true),
    Comeback: new ability_1.default("come_back", "カムバック", true),
    ColdBlooded: new ability_1.default("cold_blooded", "マーキングガード", true),
    NinjaSuquid: new ability_1.default("ninja_squid", "イカニンジャ", true),
    Haunt: new ability_1.default("haunt", "うらみ", true),
    Recon: new ability_1.default("recon", "スタートレーダー", true),
    BombSniffer: new ability_1.default("bomb_sniffer", "ボムサーチ", true),
    InkResistanceUp: new ability_1.default("ink_resistance_up", "安全シューズ", true),
    StealthJump: new ability_1.default("stealth_jump", "ステルスジャンプ", true)
};
exports.ALL_BRANDS = {
    Zink: new brand_1.default('zink', 'アイロニック', option_1.Optional(exports.ALL_ABILITIES.QuickSuperJump), option_1.Optional(exports.ALL_ABILITIES.QuickRespawn)),
    Tentatk: new brand_1.default('tentatk', 'アロメ', option_1.Optional(exports.ALL_ABILITIES.InkRecoveryUp), option_1.Optional(exports.ALL_ABILITIES.QuickSuperJump)),
    Zekko: new brand_1.default('zekko', 'エゾッコ', option_1.Optional(exports.ALL_ABILITIES.SpecialSaver), option_1.Optional(exports.ALL_ABILITIES.SpecialChargeUp)),
    KrakOn: new brand_1.default('krak_on', 'クラーゲス', option_1.Optional(exports.ALL_ABILITIES.SwimSpeedUp), option_1.Optional(exports.ALL_ABILITIES.DefenceUp)),
    Inkline: new brand_1.default('inkline', 'シグレニ', option_1.Optional(exports.ALL_ABILITIES.DefenceUp), option_1.Optional(exports.ALL_ABILITIES.DamegeUp)),
    SplashMob: new brand_1.default('splash_mob', 'ジモン', option_1.Optional(exports.ALL_ABILITIES.InkSaverMain), option_1.Optional(exports.ALL_ABILITIES.RunSpeedUp)),
    SquidForce: new brand_1.default('squid_force', 'バトロイカ', option_1.Optional(exports.ALL_ABILITIES.DamegeUp), option_1.Optional(exports.ALL_ABILITIES.InkSaverMain)),
    Forge: new brand_1.default('forge', 'フォーリマ', option_1.Optional(exports.ALL_ABILITIES.SpecialDurationUp), option_1.Optional(exports.ALL_ABILITIES.InkSaverSub)),
    Skalop: new brand_1.default('skalop', 'ホタックス', option_1.Optional(exports.ALL_ABILITIES.QuickRespawn), option_1.Optional(exports.ALL_ABILITIES.SpecialSaver)),
    Firefin: new brand_1.default('firefin', 'ホッコリー', option_1.Optional(exports.ALL_ABILITIES.InkSaverSub), option_1.Optional(exports.ALL_ABILITIES.InkRecoveryUp)),
    Takoroka: new brand_1.default('takoroka', 'ヤコ', option_1.Optional(exports.ALL_ABILITIES.SpecialChargeUp), option_1.Optional(exports.ALL_ABILITIES.SpecialDurationUp)),
    Rockenberg: new brand_1.default('rockenberg', 'ロッケンベルグ', option_1.Optional(exports.ALL_ABILITIES.RunSpeedUp), option_1.Optional(exports.ALL_ABILITIES.SwimSpeedUp)),
    Cuttlegear: new brand_1.default('cuttlegear', 'アタリメイド', option_1.Optional(null), option_1.Optional(null)),
    KOG: new brand_1.default('kog', 'KOG', option_1.Optional(null), option_1.Optional(null)),
    Amiibo: new brand_1.default('amiibo', 'amiibo', option_1.Optional(null), option_1.Optional(null)),
    TheSQUIDGIRL: new brand_1.default('the_squid_girl', '侵略！イカ娘', option_1.Optional(null), option_1.Optional(null)),
    Famitsu: new brand_1.default('famitsu', 'ファミ通', option_1.Optional(null), option_1.Optional(null))
};
exports.ALL_GEARS = [
    new gear_1.default('スカッシュバンド', exports.ALL_BRANDS.Zink, 0, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('サムライヘルメット', exports.ALL_BRANDS.Amiibo, 0, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('ダイバーゴーグル', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('でんせつのぼうし', exports.ALL_BRANDS.Cuttlegear, 0, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('ヤコメッシュ', exports.ALL_BRANDS.Takoroka, 0, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('スプラッシュゴーグル', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('チャリキング帽', exports.ALL_BRANDS.Tentatk, 0, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('パワードマスク', exports.ALL_BRANDS.Amiibo, 0, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('ショートビーニー', exports.ALL_BRANDS.Inkline, 0, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('スゲ', exports.ALL_BRANDS.Inkline, 0, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('スタジオヘッドホン', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('サファリハット', exports.ALL_BRANDS.Firefin, 0, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('バスケバンド', exports.ALL_BRANDS.Zink, 0, exports.ALL_ABILITIES.OpeningGambit),
    new gear_1.default('テッカサイクルキャップ', exports.ALL_BRANDS.Zink, 0, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('キャディ サンバイザー', exports.ALL_BRANDS.Zink, 0, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('テニスバンド', exports.ALL_BRANDS.Tentatk, 0, exports.ALL_ABILITIES.Comeback),
    new gear_1.default('イロメガネ', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.LastDitchEffort),
    new gear_1.default('エゾッコメッシュ', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('バックワードキャップ', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ランニングバンド', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('2ラインメッシュ', exports.ALL_BRANDS.KrakOn, 0, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('キャンプハット', exports.ALL_BRANDS.Inkline, 0, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('キャンプキャップ', exports.ALL_BRANDS.Inkline, 0, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('クロブチ レトロ', exports.ALL_BRANDS.SplashMob, 0, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ヘッドバンド ホワイト', exports.ALL_BRANDS.SquidForce, 0, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ウインターボンボン', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.Tenacity),
    new gear_1.default('ウーニーズBBキャップ', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('ビバレッジキャップ', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('イカンカン', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('ヤキフグ サンバイザー', exports.ALL_BRANDS.Firefin, 0, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('ジェットキャップ', exports.ALL_BRANDS.Firefin, 0, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('フグベルハット', exports.ALL_BRANDS.Firefin, 0, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ダテコンタクト', exports.ALL_BRANDS.Tentatk, 0, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('サンサンサンバイザー', exports.ALL_BRANDS.Tentatk, 0, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('5パネルキャップ', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.Comeback),
    new gear_1.default('アローバンド ブラック', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.Tenacity),
    new gear_1.default('ボンボンニット', exports.ALL_BRANDS.SplashMob, 0, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('ボーダービーニー', exports.ALL_BRANDS.SplashMob, 0, exports.ALL_ABILITIES.OpeningGambit),
    new gear_1.default('ロブスターブーニー', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.LastDitchEffort),
    new gear_1.default('オーロラヘッドホン', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('スケボーメット', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('イカベーダーキャップ', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('カモメッシュ', exports.ALL_BRANDS.Firefin, 0, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('ヒーローヘッズ レプリカ', exports.ALL_BRANDS.Cuttlegear, 0, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('タコゾネススコープ', exports.ALL_BRANDS.Cuttlegear, 0, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('イカパッチン', exports.ALL_BRANDS.Amiibo, 0, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('タイショウのはちまき', exports.ALL_BRANDS.Famitsu, 0, exports.ALL_ABILITIES.Comeback),
    new gear_1.default('イカ娘ずきん', exports.ALL_BRANDS.TheSQUIDGIRL, 0, exports.ALL_ABILITIES.OpeningGambit),
    new gear_1.default('アローバンド ホワイト', exports.ALL_BRANDS.Zekko, 0, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('タコマスク', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.Tenacity),
    new gear_1.default('パイロットゴーグル', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('フェイスゴーグル', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.Comeback),
    new gear_1.default('ナイトビジョン', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('テンタクルズメット', exports.ALL_BRANDS.Forge, 0, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('サイクルメット', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('チドリキャップ', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.OpeningGambit),
    new gear_1.default('バイザーメット', exports.ALL_BRANDS.Skalop, 0, exports.ALL_ABILITIES.LastDitchEffort),
    new gear_1.default('タレサン18K', exports.ALL_BRANDS.Rockenberg, 0, exports.ALL_ABILITIES.LastDitchEffort),
    new gear_1.default('アーマーメット　レプリカ', exports.ALL_BRANDS.Cuttlegear, 0, exports.ALL_ABILITIES.Tenacity),
    new gear_1.default('ウーニーズBBシャツ', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('アイロニックロング', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('アイロニックレイヤード', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('バスケジャージ アウェイ', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('かくれパイレーツ', exports.ALL_BRANDS.Tentatk, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('イカノメT ライトブルー', exports.ALL_BRANDS.Tentatk, 1, exports.ALL_ABILITIES.ColdBlooded),
    new gear_1.default('イカノメT ブラック', exports.ALL_BRANDS.Tentatk, 1, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('エゾッコラグラン', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('イカゴッチンベスト', exports.ALL_BRANDS.KrakOn, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('レイニーブルーT', exports.ALL_BRANDS.KrakOn, 1, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('サニーオレンジT', exports.ALL_BRANDS.KrakOn, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('ヤマビコT ブルー', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('ボーダーモスグリーン', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.NinjaSuquid),
    new gear_1.default('ヤマビコT アイボリー', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.Haunt),
    new gear_1.default('シャンブレーシャツ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('パイレーツボーダー', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('カレッジスウェット グレー', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('カレッジラグラン', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.Recon),
    new gear_1.default('さくらエビポロ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.NinjaSuquid),
    new gear_1.default('マリンボーダー', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('よもぎポロ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.ColdBlooded),
    new gear_1.default('レタード　オレンジ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('カレッジスウェット　ネイビー', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('イカバッテンロング', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.Haunt),
    new gear_1.default('イカホワイト', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('イカブラック', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('わかばイカT', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('イカバッテンマスタード', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('レイヤード ホワイト', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('レイヤード ブラック', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('マスタードガサネ', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('カモガサネ', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('おどるイカアロハ', exports.ALL_BRANDS.Forge, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('グレープT', exports.ALL_BRANDS.Skalop, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ミントT', exports.ALL_BRANDS.Skalop, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('チドリメロンＴ', exports.ALL_BRANDS.Skalop, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('ヤキフグ8bit ホワイト', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.Recon),
    new gear_1.default('ニクショクT', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('ヤキフグ8bit ブラック', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('トリコロールラガー', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ベクトルパターン グレー', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('ベクトルパターン レッド', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('ハラグロラグラン', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('マルエリシャツ', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('ロッケンベルグT ブラック', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('ハラシロラグラン', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('ドカンT ブラック', exports.ALL_BRANDS.KOG, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ラインT ホワイト', exports.ALL_BRANDS.KOG, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('テッカサイクルシャツ', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.ColdBlooded),
    new gear_1.default('スクールジャージー', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.NinjaSuquid),
    new gear_1.default('バスケジャージ ホーム', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ギンガムチェック アカ', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('バニーポップ ブラック', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('エゾッコパーカー アズキ', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.NinjaSuquid),
    new gear_1.default('ロゴマシマシアロハ', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ミックスシャツグレー', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('ギンガムチェック ミドリ', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('マウンテンベリー', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('ブロックストライプシャツ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('レタード　グリーン', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.Recon),
    new gear_1.default('ボーダーホワイト', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ボーダーネイビー', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('ベイビークラゲシャツ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('シロシャツ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('イカリスウェット', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.ColdBlooded),
    new gear_1.default('ガチブラック', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.Recon),
    new gear_1.default('グリーンＴ', exports.ALL_BRANDS.Forge, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ホッコリー ネイビー', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('アーバンベスト イエロー', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.Haunt),
    new gear_1.default('ジップアップ グリーン', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('ベクトルラインガサネ', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('オレンジボーダーラガー', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('チョコガサネ', exports.ALL_BRANDS.Takoroka, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('ロッケンベルグT ホワイト', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ヒーロージャケット レプリカ', exports.ALL_BRANDS.Cuttlegear, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('タコゾネスプロテクター', exports.ALL_BRANDS.Cuttlegear, 1, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('パワードスーツ', exports.ALL_BRANDS.Amiibo, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('サムライジャケット', exports.ALL_BRANDS.Amiibo, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('スクールブレザー', exports.ALL_BRANDS.Amiibo, 1, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('タイショウのまえかけ', exports.ALL_BRANDS.Famitsu, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('イカ娘ノースリーブ', exports.ALL_BRANDS.TheSQUIDGIRL, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('FCジャージー', exports.ALL_BRANDS.Zink, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('チャリキングジャージ', exports.ALL_BRANDS.Tentatk, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('スタジャンロゴマシ', exports.ALL_BRANDS.Zekko, 1, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('マウンテンダウン', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('マウンテンオリーブ', exports.ALL_BRANDS.Inkline, 1, exports.ALL_ABILITIES.Recon),
    new gear_1.default('タイシャツ', exports.ALL_BRANDS.SplashMob, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ガチガサネ', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('ガチホワイト', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.NinjaSuquid),
    new gear_1.default('レトロジャッジ', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('フェスT', exports.ALL_BRANDS.SquidForce, 1, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ミスターベースボール', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('ジップアップ カモ', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('アーバンベスト ナイト', exports.ALL_BRANDS.Firefin, 1, exports.ALL_ABILITIES.ColdBlooded),
    new gear_1.default('イカライダーBLACK', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('イカライダーWHITE', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('ヴィンテージチェック', exports.ALL_BRANDS.Rockenberg, 1, exports.ALL_ABILITIES.Haunt),
    new gear_1.default('タコT', exports.ALL_BRANDS.Cuttlegear, 1, exports.ALL_ABILITIES.Haunt),
    new gear_1.default('アーマージャケット　レプリカ', exports.ALL_BRANDS.Cuttlegear, 1, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('シーホースHi ゾンビ', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('シーホースHi レッド', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('シーホース ホワイト', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('シーホースHi パープル', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('ブラックビーンズ', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ウミウシパープル', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('ピンクビーンズ', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('シアンビーンズ', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('ウミウシイエロー', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.InkResistanceUp),
    new gear_1.default('グリッチョ オレンジ', exports.ALL_BRANDS.Zekko, 2, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('グリッチョ ブルー', exports.ALL_BRANDS.Zekko, 2, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('スリッポン レッド', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('キャンバス ホワイト', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ブルーベリーコンフォート', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('オイスタークロッグ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('キャンバス クマノミ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('キャンバス バナナ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.BombSniffer),
    new gear_1.default('キャンバスHi マッシュルーム', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.StealthJump),
    new gear_1.default('キャンバスHi モロヘイヤ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('スリッポン ブルー', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('レイニーアセロラ', exports.ALL_BRANDS.Inkline, 2, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('ベリベリレッド', exports.ALL_BRANDS.SplashMob, 2, exports.ALL_ABILITIES.InkResistanceUp),
    new gear_1.default('オレンジアローズ', exports.ALL_BRANDS.Takoroka, 2, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('ラバーソール ホワイト', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('イカスミチップ', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('シーホース イエロー', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.BombSniffer),
    new gear_1.default('シーホースHi ゴールド', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('シーホース ブラックレザー', exports.ALL_BRANDS.Zink, 2, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('スリッポン チドリ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.DefenceUp),
    new gear_1.default('チョコクロッグ', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('キャンバスHi トマト', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.InkResistanceUp),
    new gear_1.default('アケビコンフォート', exports.ALL_BRANDS.KrakOn, 2, exports.ALL_ABILITIES.DamegeUp),
    new gear_1.default('レイニーモスグリーン', exports.ALL_BRANDS.Inkline, 2, exports.ALL_ABILITIES.StealthJump),
    new gear_1.default('トレッキングカスタム', exports.ALL_BRANDS.Inkline, 2, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('トレッキングライト', exports.ALL_BRANDS.Inkline, 2, exports.ALL_ABILITIES.InkRecoveryUp),
    new gear_1.default('ホワイトアローズ', exports.ALL_BRANDS.Takoroka, 2, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('ラバーソール チェリー', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.StealthJump),
    new gear_1.default('ヌバックブーツ イエロー', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.BombRangeUp),
    new gear_1.default('モトクロスブーツ', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.QuickRespawn),
    new gear_1.default('ラバーソール ターコイズ', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('ロッキンホワイト', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.SpecialChargeUp),
    new gear_1.default('タコゾネスブーツ', exports.ALL_BRANDS.Cuttlegear, 2, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('ヒーローキックス レプリカ', exports.ALL_BRANDS.Cuttlegear, 2, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('パワードレッグス', exports.ALL_BRANDS.Amiibo, 2, exports.ALL_ABILITIES.InkSaverMain),
    new gear_1.default('サムライシューズ', exports.ALL_BRANDS.Amiibo, 2, exports.ALL_ABILITIES.SpecialDurationUp),
    new gear_1.default('スクールローファー', exports.ALL_BRANDS.Amiibo, 2, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('タイショウのげた', exports.ALL_BRANDS.Famitsu, 2, exports.ALL_ABILITIES.RunSpeedUp),
    new gear_1.default('イカ娘シューズ', exports.ALL_BRANDS.TheSQUIDGIRL, 2, exports.ALL_ABILITIES.SwimSpeedUp),
    new gear_1.default('ウミウシレッド', exports.ALL_BRANDS.Tentatk, 2, exports.ALL_ABILITIES.SpecialSaver),
    new gear_1.default('グリッチョ グリーン 限定版', exports.ALL_BRANDS.Zekko, 2, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('トレッキングプロ', exports.ALL_BRANDS.Inkline, 2, exports.ALL_ABILITIES.BombSniffer),
    new gear_1.default('ベリベリホワイト', exports.ALL_BRANDS.SplashMob, 2, exports.ALL_ABILITIES.InkSaverSub),
    new gear_1.default('ユデスパイカ', exports.ALL_BRANDS.Takoroka, 2, exports.ALL_ABILITIES.BombSniffer),
    new gear_1.default('クレイジーアローズ', exports.ALL_BRANDS.Takoroka, 2, exports.ALL_ABILITIES.StealthJump),
    new gear_1.default('ヌバックブーツ レッド', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.QuickSuperJump),
    new gear_1.default('モトクロス ソリッドブルー', exports.ALL_BRANDS.Rockenberg, 2, exports.ALL_ABILITIES.InkResistanceUp),
    new gear_1.default('アーマーブーツ レプリカ', exports.ALL_BRANDS.Cuttlegear, 2, exports.ALL_ABILITIES.QuickRespawn)
];
