import {Optional} from "../domain/option";
import Ability from "../domain/ability";
import Brand from "../domain/brand";
import Gear from "../domain/gear";
import GearType from "../domain/gear_type";

export const ALL_ABILITIES = {
    damage_up: new Ability("damage_up", "攻撃力アップ", false),
    defence_up: new Ability("defence_up", "防御力アップ", false),
    ink_saver_main: new Ability("ink_saver_main", "インク効率アップ（メイン）", false),
    ink_saver_sub: new Ability("ink_saver_sub", "インク効率アップ（サブ）", false),
    ink_recovery_up: new Ability("ink_recovery_up", "インク回復力アップ", false),
    run_speed_up: new Ability("run_speed_up", "ヒト移動速度アップ", false),
    swim_speed_up: new Ability("swim_speed_up", "イカダッシュ速度アップ", false),
    special_charge_up: new Ability("special_charge_up", "スペシャル増加量アップ", false),
    special_duration_up: new Ability("special_duration_up", "スペシャル時間延長", false),
    quick_respawn: new Ability("quick_respawn", "復活時間短縮", false),
    special_saver: new Ability("special_saver", "スペシャル減少量ダウン", false),
    quick_super_jump: new Ability("quick_super_jump", "スーパージャンプ時間短縮", false),
    bomb_range_up: new Ability("bomb_range_up", "ボム飛距離アップ", true),
    opening_gambit: new Ability("opening_gambit", "スタートダッシュ", true),
    last_ditch_effort: new Ability("last_ditch_effort", "ラストスパート", true),
    tenacity: new Ability("tenacity", "逆境強化", true),
    come_back: new Ability("come_back", "カムバック", true),
    cold_blooded: new Ability("cold_blooded", "マーキングガード", true),
    ninja_squid: new Ability("ninja_squid", "イカニンジャ", true),
    haunt: new Ability("haunt", "うらみ", true),
    recon: new Ability("recon", "スタートレーダー", true),
    bomb_sniffer: new Ability("bomb_sniffer", "ボムサーチ", true),
    ink_resistance_up: new Ability("ink_resistance_up", "安全シューズ", true),
    stealth_jump: new Ability("stealth_jump", "ステルスジャンプ", true)
}
export const ALL_BRANDS = {
    Zink: new Brand('zink', 'アイロニック', Optional(ALL_ABILITIES.quick_super_jump), Optional(ALL_ABILITIES.quick_respawn)),
    Tentatk: new Brand('tentatk', 'アロメ', Optional(ALL_ABILITIES.ink_recovery_up), Optional(ALL_ABILITIES.quick_super_jump)),
    Zekko: new Brand('zekko', 'エゾッコ', Optional(ALL_ABILITIES.special_saver), Optional(ALL_ABILITIES.special_charge_up)),
    KrakOn: new Brand('krak_on', 'クラーゲス', Optional(ALL_ABILITIES.swim_speed_up), Optional(ALL_ABILITIES.defence_up)),
    Inkline: new Brand('inkline', 'シグレニ', Optional(ALL_ABILITIES.defence_up), Optional(ALL_ABILITIES.damage_up)),
    SplashMob: new Brand('splash_mob', 'ジモン', Optional(ALL_ABILITIES.ink_saver_main), Optional(ALL_ABILITIES.run_speed_up)),
    SquidForce: new Brand('squid_force', 'バトロイカ', Optional(ALL_ABILITIES.damage_up), Optional(ALL_ABILITIES.ink_saver_main)),
    Forge: new Brand('forge', 'フォーリマ', Optional(ALL_ABILITIES.special_duration_up), Optional(ALL_ABILITIES.ink_saver_sub)),
    Skalop: new Brand('skalop', 'ホタックス', Optional(ALL_ABILITIES.quick_respawn), Optional(ALL_ABILITIES.special_saver)),
    Firefin: new Brand('firefin', 'ホッコリー', Optional(ALL_ABILITIES.ink_saver_sub), Optional(ALL_ABILITIES.ink_recovery_up)),
    Takoroka: new Brand('takoroka', 'ヤコ', Optional(ALL_ABILITIES.special_charge_up), Optional(ALL_ABILITIES.special_duration_up)),
    Rockenberg: new Brand('rockenberg', 'ロッケンベルグ', Optional(ALL_ABILITIES.run_speed_up), Optional(ALL_ABILITIES.swim_speed_up)),
    Cuttlegear: new Brand('cuttlegear', 'アタリメイド', Optional(null), Optional(null)),
    KOG: new Brand('kog', 'KOG', Optional(null), Optional(null)),
    Amiibo: new Brand('amiibo', 'amiibo', Optional(null), Optional(null)),
    TheSQUIDGIRL: new Brand('the_squid_girl', '侵略！イカ娘', Optional(null), Optional(null)),
    Famitsu: new Brand('famitsu', 'ファミ通', Optional(null), Optional(null))
};

export const ALL_GEARS = [
    new Gear('スカッシュバンド', ALL_BRANDS.Zink, GearType.HeadGear, ALL_ABILITIES.damage_up),
    new Gear('サムライヘルメット', ALL_BRANDS.Amiibo, GearType.HeadGear, ALL_ABILITIES.damage_up),
    new Gear('ダイバーゴーグル', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.damage_up),
    new Gear('でんせつのぼうし', ALL_BRANDS.Cuttlegear, GearType.HeadGear, ALL_ABILITIES.damage_up),
    new Gear('ヤコメッシュ', ALL_BRANDS.Takoroka, GearType.HeadGear, ALL_ABILITIES.defence_up),
    new Gear('スプラッシュゴーグル', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.defence_up),
    new Gear('チャリキング帽', ALL_BRANDS.Tentatk, GearType.HeadGear, ALL_ABILITIES.defence_up),
    new Gear('パワードマスク', ALL_BRANDS.Amiibo, GearType.HeadGear, ALL_ABILITIES.defence_up),
    new Gear('ショートビーニー', ALL_BRANDS.Inkline, GearType.HeadGear, ALL_ABILITIES.ink_saver_main),
    new Gear('スゲ', ALL_BRANDS.Inkline, GearType.HeadGear, ALL_ABILITIES.ink_saver_main),
    new Gear('スタジオヘッドホン', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.ink_saver_main),
    new Gear('サファリハット', ALL_BRANDS.Firefin, GearType.HeadGear, ALL_ABILITIES.ink_saver_main),
    new Gear('バスケバンド', ALL_BRANDS.Zink, GearType.HeadGear, ALL_ABILITIES.opening_gambit),
    new Gear('テッカサイクルキャップ', ALL_BRANDS.Zink, GearType.HeadGear, ALL_ABILITIES.bomb_range_up),
    new Gear('キャディ サンバイザー', ALL_BRANDS.Zink, GearType.HeadGear, ALL_ABILITIES.run_speed_up),
    new Gear('テニスバンド', ALL_BRANDS.Tentatk, GearType.HeadGear, ALL_ABILITIES.come_back),
    new Gear('イロメガネ', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.last_ditch_effort),
    new Gear('エゾッコメッシュ', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.quick_super_jump),
    new Gear('バックワードキャップ', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.quick_respawn),
    new Gear('ランニングバンド', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.ink_saver_sub),
    new Gear('2ラインメッシュ', ALL_BRANDS.KrakOn, GearType.HeadGear, ALL_ABILITIES.special_saver),
    new Gear('キャンプハット', ALL_BRANDS.Inkline, GearType.HeadGear, ALL_ABILITIES.special_duration_up),
    new Gear('キャンプキャップ', ALL_BRANDS.Inkline, GearType.HeadGear, ALL_ABILITIES.swim_speed_up),
    new Gear('クロブチ レトロ', ALL_BRANDS.SplashMob, GearType.HeadGear, ALL_ABILITIES.quick_respawn),
    new Gear('ヘッドバンド ホワイト', ALL_BRANDS.SquidForce, GearType.HeadGear, ALL_ABILITIES.ink_recovery_up),
    new Gear('ウインターボンボン', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.tenacity),
    new Gear('ウーニーズBBキャップ', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.bomb_range_up),
    new Gear('ビバレッジキャップ', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.ink_saver_sub),
    new Gear('イカンカン', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.quick_super_jump),
    new Gear('ヤキフグ サンバイザー', ALL_BRANDS.Firefin, GearType.HeadGear, ALL_ABILITIES.special_charge_up),
    new Gear('ジェットキャップ', ALL_BRANDS.Firefin, GearType.HeadGear, ALL_ABILITIES.special_saver),
    new Gear('フグベルハット', ALL_BRANDS.Firefin, GearType.HeadGear, ALL_ABILITIES.ink_recovery_up),
    new Gear('ダテコンタクト', ALL_BRANDS.Tentatk, GearType.HeadGear, ALL_ABILITIES.special_charge_up),
    new Gear('サンサンサンバイザー', ALL_BRANDS.Tentatk, GearType.HeadGear, ALL_ABILITIES.bomb_range_up),
    new Gear('5パネルキャップ', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.come_back),
    new Gear('アローバンド ブラック', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.tenacity),
    new Gear('ボンボンニット', ALL_BRANDS.SplashMob, GearType.HeadGear, ALL_ABILITIES.quick_super_jump),
    new Gear('ボーダービーニー', ALL_BRANDS.SplashMob, GearType.HeadGear, ALL_ABILITIES.opening_gambit),
    new Gear('ロブスターブーニー', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.last_ditch_effort),
    new Gear('オーロラヘッドホン', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.ink_saver_sub),
    new Gear('スケボーメット', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.special_saver),
    new Gear('イカベーダーキャップ', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.special_charge_up),
    new Gear('カモメッシュ', ALL_BRANDS.Firefin, GearType.HeadGear, ALL_ABILITIES.swim_speed_up),
    new Gear('ヒーローヘッズ レプリカ', ALL_BRANDS.Cuttlegear, GearType.HeadGear, ALL_ABILITIES.run_speed_up),
    new Gear('タコゾネススコープ', ALL_BRANDS.Cuttlegear, GearType.HeadGear, ALL_ABILITIES.bomb_range_up),
    new Gear('イカパッチン', ALL_BRANDS.Amiibo, GearType.HeadGear, ALL_ABILITIES.swim_speed_up),
    new Gear('タイショウのはちまき', ALL_BRANDS.Famitsu, GearType.HeadGear, ALL_ABILITIES.come_back),
    new Gear('イカ娘ずきん', ALL_BRANDS.TheSQUIDGIRL, GearType.HeadGear, ALL_ABILITIES.opening_gambit),
    new Gear('アローバンド ホワイト', ALL_BRANDS.Zekko, GearType.HeadGear, ALL_ABILITIES.special_duration_up),
    new Gear('タコマスク', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.tenacity),
    new Gear('パイロットゴーグル', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.bomb_range_up),
    new Gear('フェイスゴーグル', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.come_back),
    new Gear('ナイトビジョン', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.swim_speed_up),
    new Gear('テンタクルズメット', ALL_BRANDS.Forge, GearType.HeadGear, ALL_ABILITIES.run_speed_up),
    new Gear('サイクルメット', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.ink_recovery_up),
    new Gear('チドリキャップ', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.opening_gambit),
    new Gear('バイザーメット', ALL_BRANDS.Skalop, GearType.HeadGear, ALL_ABILITIES.last_ditch_effort),
    new Gear('タレサン18K', ALL_BRANDS.Rockenberg, GearType.HeadGear, ALL_ABILITIES.last_ditch_effort),
    new Gear('アーマーメット　レプリカ', ALL_BRANDS.Cuttlegear, GearType.HeadGear, ALL_ABILITIES.tenacity),
    new Gear('ウーニーズBBシャツ', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.run_speed_up),
    new Gear('アイロニックロング', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('アイロニックレイヤード', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('バスケジャージ アウェイ', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('かくれパイレーツ', ALL_BRANDS.Tentatk, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('イカノメT ライトブルー', ALL_BRANDS.Tentatk, GearType.Clothing, ALL_ABILITIES.cold_blooded),
    new Gear('イカノメT ブラック', ALL_BRANDS.Tentatk, GearType.Clothing, ALL_ABILITIES.run_speed_up),
    new Gear('エゾッコラグラン', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('イカゴッチンベスト', ALL_BRANDS.KrakOn, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('レイニーブルーT', ALL_BRANDS.KrakOn, GearType.Clothing, ALL_ABILITIES.ink_saver_main),
    new Gear('サニーオレンジT', ALL_BRANDS.KrakOn, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('ヤマビコT ブルー', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('ボーダーモスグリーン', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.ninja_squid),
    new Gear('ヤマビコT アイボリー', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.haunt),
    new Gear('シャンブレーシャツ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.bomb_range_up),
    new Gear('パイレーツボーダー', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('カレッジスウェット グレー', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('カレッジラグラン', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.recon),
    new Gear('さくらエビポロ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.ninja_squid),
    new Gear('マリンボーダー', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.run_speed_up),
    new Gear('よもぎポロ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.cold_blooded),
    new Gear('レタード　オレンジ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('カレッジスウェット　ネイビー', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('イカバッテンロング', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.haunt),
    new Gear('イカホワイト', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('イカブラック', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('わかばイカT', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('イカバッテンマスタード', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.bomb_range_up),
    new Gear('レイヤード ホワイト', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('レイヤード ブラック', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.ink_saver_main),
    new Gear('マスタードガサネ', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('カモガサネ', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('おどるイカアロハ', ALL_BRANDS.Forge, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('グレープT', ALL_BRANDS.Skalop, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('ミントT', ALL_BRANDS.Skalop, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('チドリメロンＴ', ALL_BRANDS.Skalop, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('ヤキフグ8bit ホワイト', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.recon),
    new Gear('ニクショクT', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('ヤキフグ8bit ブラック', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('トリコロールラガー', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('ベクトルパターン グレー', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('ベクトルパターン レッド', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.ink_saver_main),
    new Gear('ハラグロラグラン', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('マルエリシャツ', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('ロッケンベルグT ブラック', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('ハラシロラグラン', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('ドカンT ブラック', ALL_BRANDS.KOG, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('ラインT ホワイト', ALL_BRANDS.KOG, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('テッカサイクルシャツ', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.cold_blooded),
    new Gear('スクールジャージー', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.ninja_squid),
    new Gear('バスケジャージ ホーム', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('ギンガムチェック アカ', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.ink_saver_main),
    new Gear('バニーポップ ブラック', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('エゾッコパーカー アズキ', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.ninja_squid),
    new Gear('ロゴマシマシアロハ', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('ミックスシャツグレー', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('ギンガムチェック ミドリ', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.bomb_range_up),
    new Gear('マウンテンベリー', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('ブロックストライプシャツ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.quick_super_jump),
    new Gear('レタード　グリーン', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.recon),
    new Gear('ボーダーホワイト', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('ボーダーネイビー', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('ベイビークラゲシャツ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('シロシャツ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('イカリスウェット', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.cold_blooded),
    new Gear('ガチブラック', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.recon),
    new Gear('グリーンＴ', ALL_BRANDS.Forge, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('ホッコリー ネイビー', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.bomb_range_up),
    new Gear('アーバンベスト イエロー', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.haunt),
    new Gear('ジップアップ グリーン', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('ベクトルラインガサネ', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('オレンジボーダーラガー', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.run_speed_up),
    new Gear('チョコガサネ', ALL_BRANDS.Takoroka, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('ロッケンベルグT ホワイト', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('ヒーロージャケット レプリカ', ALL_BRANDS.Cuttlegear, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('タコゾネスプロテクター', ALL_BRANDS.Cuttlegear, GearType.Clothing, ALL_ABILITIES.ink_saver_sub),
    new Gear('パワードスーツ', ALL_BRANDS.Amiibo, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('サムライジャケット', ALL_BRANDS.Amiibo, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('スクールブレザー', ALL_BRANDS.Amiibo, GearType.Clothing, ALL_ABILITIES.ink_recovery_up),
    new Gear('タイショウのまえかけ', ALL_BRANDS.Famitsu, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('イカ娘ノースリーブ', ALL_BRANDS.TheSQUIDGIRL, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('FCジャージー', ALL_BRANDS.Zink, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('チャリキングジャージ', ALL_BRANDS.Tentatk, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('スタジャンロゴマシ', ALL_BRANDS.Zekko, GearType.Clothing, ALL_ABILITIES.damage_up),
    new Gear('マウンテンダウン', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.swim_speed_up),
    new Gear('マウンテンオリーブ', ALL_BRANDS.Inkline, GearType.Clothing, ALL_ABILITIES.recon),
    new Gear('タイシャツ', ALL_BRANDS.SplashMob, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('ガチガサネ', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.run_speed_up),
    new Gear('ガチホワイト', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.ninja_squid),
    new Gear('レトロジャッジ', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.defence_up),
    new Gear('フェスT', ALL_BRANDS.SquidForce, GearType.Clothing, ALL_ABILITIES.special_saver),
    new Gear('ミスターベースボール', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('ジップアップ カモ', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.quick_respawn),
    new Gear('アーバンベスト ナイト', ALL_BRANDS.Firefin, GearType.Clothing, ALL_ABILITIES.cold_blooded),
    new Gear('イカライダーBLACK', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.bomb_range_up),
    new Gear('イカライダーWHITE', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.special_duration_up),
    new Gear('ヴィンテージチェック', ALL_BRANDS.Rockenberg, GearType.Clothing, ALL_ABILITIES.haunt),
    new Gear('タコT', ALL_BRANDS.Cuttlegear, GearType.Clothing, ALL_ABILITIES.haunt),
    new Gear('アーマージャケット　レプリカ', ALL_BRANDS.Cuttlegear, GearType.Clothing, ALL_ABILITIES.special_charge_up),
    new Gear('シーホースHi ゾンビ', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.special_charge_up),
    new Gear('シーホースHi レッド', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.ink_saver_main),
    new Gear('シーホース ホワイト', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.ink_recovery_up),
    new Gear('シーホースHi パープル', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.special_duration_up),
    new Gear('ブラックビーンズ', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.quick_respawn),
    new Gear('ウミウシパープル', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.run_speed_up),
    new Gear('ピンクビーンズ', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.bomb_range_up),
    new Gear('シアンビーンズ', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.damage_up),
    new Gear('ウミウシイエロー', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.ink_resistance_up),
    new Gear('グリッチョ オレンジ', ALL_BRANDS.Zekko, GearType.Shoes, ALL_ABILITIES.swim_speed_up),
    new Gear('グリッチョ ブルー', ALL_BRANDS.Zekko, GearType.Shoes, ALL_ABILITIES.defence_up),
    new Gear('スリッポン レッド', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.quick_super_jump),
    new Gear('キャンバス ホワイト', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.special_saver),
    new Gear('ブルーベリーコンフォート', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.ink_saver_sub),
    new Gear('オイスタークロッグ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.run_speed_up),
    new Gear('キャンバス クマノミ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.special_charge_up),
    new Gear('キャンバス バナナ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.bomb_sniffer),
    new Gear('キャンバスHi マッシュルーム', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.stealth_jump),
    new Gear('キャンバスHi モロヘイヤ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.ink_recovery_up),
    new Gear('スリッポン ブルー', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.bomb_range_up),
    new Gear('レイニーアセロラ', ALL_BRANDS.Inkline, GearType.Shoes, ALL_ABILITIES.run_speed_up),
    new Gear('ベリベリレッド', ALL_BRANDS.SplashMob, GearType.Shoes, ALL_ABILITIES.ink_resistance_up),
    new Gear('オレンジアローズ', ALL_BRANDS.Takoroka, GearType.Shoes, ALL_ABILITIES.ink_saver_main),
    new Gear('ラバーソール ホワイト', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.swim_speed_up),
    new Gear('イカスミチップ', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.quick_respawn),
    new Gear('シーホース イエロー', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.bomb_sniffer),
    new Gear('シーホースHi ゴールド', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.run_speed_up),
    new Gear('シーホース ブラックレザー', ALL_BRANDS.Zink, GearType.Shoes, ALL_ABILITIES.swim_speed_up),
    new Gear('スリッポン チドリ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.defence_up),
    new Gear('チョコクロッグ', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.quick_respawn),
    new Gear('キャンバスHi トマト', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.ink_resistance_up),
    new Gear('アケビコンフォート', ALL_BRANDS.KrakOn, GearType.Shoes, ALL_ABILITIES.damage_up),
    new Gear('レイニーモスグリーン', ALL_BRANDS.Inkline, GearType.Shoes, ALL_ABILITIES.stealth_jump),
    new Gear('トレッキングカスタム', ALL_BRANDS.Inkline, GearType.Shoes, ALL_ABILITIES.special_duration_up),
    new Gear('トレッキングライト', ALL_BRANDS.Inkline, GearType.Shoes, ALL_ABILITIES.ink_recovery_up),
    new Gear('ホワイトアローズ', ALL_BRANDS.Takoroka, GearType.Shoes, ALL_ABILITIES.special_duration_up),
    new Gear('ラバーソール チェリー', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.stealth_jump),
    new Gear('ヌバックブーツ イエロー', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.bomb_range_up),
    new Gear('モトクロスブーツ', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.quick_respawn),
    new Gear('ラバーソール ターコイズ', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.special_charge_up),
    new Gear('ロッキンホワイト', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.special_charge_up),
    new Gear('タコゾネスブーツ', ALL_BRANDS.Cuttlegear, GearType.Shoes, ALL_ABILITIES.special_saver),
    new Gear('ヒーローキックス レプリカ', ALL_BRANDS.Cuttlegear, GearType.Shoes, ALL_ABILITIES.quick_super_jump),
    new Gear('パワードレッグス', ALL_BRANDS.Amiibo, GearType.Shoes, ALL_ABILITIES.ink_saver_main),
    new Gear('サムライシューズ', ALL_BRANDS.Amiibo, GearType.Shoes, ALL_ABILITIES.special_duration_up),
    new Gear('スクールローファー', ALL_BRANDS.Amiibo, GearType.Shoes, ALL_ABILITIES.ink_saver_sub),
    new Gear('タイショウのげた', ALL_BRANDS.Famitsu, GearType.Shoes, ALL_ABILITIES.run_speed_up),
    new Gear('イカ娘シューズ', ALL_BRANDS.TheSQUIDGIRL, GearType.Shoes, ALL_ABILITIES.swim_speed_up),
    new Gear('ウミウシレッド', ALL_BRANDS.Tentatk, GearType.Shoes, ALL_ABILITIES.special_saver),
    new Gear('グリッチョ グリーン 限定版', ALL_BRANDS.Zekko, GearType.Shoes, ALL_ABILITIES.ink_saver_sub),
    new Gear('トレッキングプロ', ALL_BRANDS.Inkline, GearType.Shoes, ALL_ABILITIES.bomb_sniffer),
    new Gear('ベリベリホワイト', ALL_BRANDS.SplashMob, GearType.Shoes, ALL_ABILITIES.ink_saver_sub),
    new Gear('ユデスパイカ', ALL_BRANDS.Takoroka, GearType.Shoes, ALL_ABILITIES.bomb_sniffer),
    new Gear('クレイジーアローズ', ALL_BRANDS.Takoroka, GearType.Shoes, ALL_ABILITIES.stealth_jump),
    new Gear('ヌバックブーツ レッド', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.quick_super_jump),
    new Gear('モトクロス ソリッドブルー', ALL_BRANDS.Rockenberg, GearType.Shoes, ALL_ABILITIES.ink_resistance_up),
    new Gear('アーマーブーツ レプリカ', ALL_BRANDS.Cuttlegear, GearType.Shoes, ALL_ABILITIES.quick_respawn)
];
